export const metadata = {
  title: 'Terms of Service — MomzVeda',
};

export default function TermsOfService() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px', fontFamily: "'DM Sans', sans-serif", color: '#1A2E23', lineHeight: 1.8 }}>
      <a href="/" style={{ color: '#22C55E', textDecoration: 'none', fontSize: 14, fontWeight: 600 }}>← Back to MomzVeda</a>

      <h1 style={{ fontSize: 32, fontWeight: 700, marginTop: 24, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ color: '#6B9A7E', marginBottom: 32 }}>Last updated: February 2026</p>

      <div style={{ background: '#FEF3C7', border: '1px solid #F59E0B', borderRadius: 12, padding: 20, marginBottom: 32 }}>
        <p style={{ fontWeight: 700, color: '#92400E', margin: 0, marginBottom: 8, fontSize: 15 }}>⚠️ IMPORTANT — PLEASE READ CAREFULLY BEFORE USING MOMZVEDA</p>
        <p style={{ margin: 0, color: '#78350F', fontSize: 14 }}>
          By accessing, downloading, or using MomzVeda in any way, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service in their entirety. If you do not agree with any part of these terms, you must immediately stop using the Service. These terms contain important disclaimers, limitations of liability, and an assumption of risk clause.
        </p>
      </div>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>1. Acceptance of Terms</h2>
      <p>By accessing, browsing, downloading, installing, or using MomzVeda ("the Service," "the App," "the Platform"), whether before or after downloading, you ("the User," "you," "your") agree to be legally bound by these Terms of Service ("Terms"). These Terms constitute a legally binding agreement between you and MomzVeda ("we," "us," "our," "the Company"). If you are using the Service on behalf of another person, you represent that you have the authority to bind that person to these Terms.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>2. Description of Service</h2>
      <p>MomzVeda is an AI-powered conversational platform that provides general parenting tips, emotional support, recipe suggestions, affirmations, and guided informational content for parents and caregivers. The Service is powered entirely by artificial intelligence and does not involve real human professionals, counselors, doctors, therapists, psychologists, or licensed practitioners of any kind.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12, color: '#DC2626' }}>3. CRITICAL DISCLAIMER — NOT PROFESSIONAL ADVICE</h2>
      <div style={{ background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <p style={{ fontWeight: 700, margin: 0, marginBottom: 12 }}>ALL CONTENT PROVIDED BY MOMZVEDA IS FOR GENERAL INFORMATIONAL AND ENTERTAINMENT PURPOSES ONLY.</p>
        <p style={{ margin: 0, marginBottom: 12 }}>The parenting tips, suggestions, guided journeys, recipes, affirmations, and any other content or responses provided by MomzVeda are general tips only. They are not tailored to your specific situation, your child's specific needs, or your family's unique circumstances.</p>
        <p style={{ margin: 0, marginBottom: 12 }}>MomzVeda does NOT provide and shall NEVER be construed as providing:</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Medical advice, diagnosis, or treatment of any kind</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Psychological, psychiatric, or mental health counseling or therapy</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Nutritional or dietary advice for you or your child(ren)</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Developmental assessments or evaluations for children</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Emergency or crisis intervention services</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Legal, financial, or professional advice of any nature</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• A substitute for the judgment of qualified professionals</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 12 }}>• A replacement for your own parental judgment and instincts</p>
        <p style={{ margin: 0, fontWeight: 700 }}>ALWAYS consult a qualified physician, pediatrician, licensed therapist, or other appropriate professional for any questions or concerns regarding your health, your child's health, development, behavior, nutrition, or wellbeing.</p>
      </div>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>4. AI-Generated Content Disclaimer</h2>
      <p>All responses and content provided by MomzVeda are generated by artificial intelligence. AI-generated content may be inaccurate, incomplete, outdated, misleading, or inappropriate for your specific situation. AI technology has inherent limitations and can produce errors, hallucinations, or incorrect information. You should independently verify any information provided by the Service before relying on it or acting upon it. MomzVeda makes no representations or warranties regarding the accuracy, reliability, completeness, or timeliness of any AI-generated content.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12, color: '#DC2626' }}>5. COMPLETE LIMITATION OF LIABILITY</h2>
      <div style={{ background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <p style={{ fontWeight: 700, margin: 0, marginBottom: 12 }}>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
        <p style={{ margin: 0, marginBottom: 12 }}>MomzVeda, its owners, operators, affiliates, employees, agents, partners, licensors, and service providers (collectively, "MomzVeda Parties") shall NOT be responsible or liable, directly or indirectly, for ANY harm, injury, loss, damage, cost, expense, claim, or liability of any kind whatsoever, whether direct, indirect, incidental, consequential, special, exemplary, punitive, or otherwise, arising out of or in connection with:</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Your use of or reliance on the Service or any content provided by the Service</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Any actions taken or decisions made based on information from the Service</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Any harm, injury, or adverse outcome to you, your child(ren), your family members, or any other person in any shape or form</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Any physical, emotional, psychological, developmental, or other harm to any adult, parent, caregiver, mother, father, child, infant, toddler, or any other individual</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Application of any parenting tips, suggestions, recipes, or guidance provided by the Service</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Allergic reactions, dietary issues, or adverse effects from any recipe or food suggestion</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Failure to seek timely professional medical, psychological, or emergency care</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Inaccurate, incomplete, outdated, or misleading AI-generated content</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Service interruptions, errors, bugs, or technical malfunctions</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Unauthorized access to or alteration of your data</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 12 }}>• Any other matter relating to the Service, regardless of the theory of liability</p>
        <p style={{ margin: 0, fontWeight: 700 }}>This limitation applies regardless of whether the alleged liability is based on contract, tort (including negligence), strict liability, or any other legal theory, even if MomzVeda has been advised of the possibility of such damage, and even if a limited remedy set forth herein is found to have failed its essential purpose.</p>
      </div>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12, color: '#DC2626' }}>6. ASSUMPTION OF RISK</h2>
      <div style={{ background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <p style={{ margin: 0, marginBottom: 12 }}>BY USING MOMZVEDA, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT:</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• You use the Service entirely at your own risk</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• You are solely responsible for all parenting and caregiving decisions for your child(ren)</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• You are solely responsible for evaluating the appropriateness, safety, and suitability of any information, tip, suggestion, or content provided by the Service for your specific situation</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• You voluntarily assume all risks associated with using or relying on information from the Service</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• The Service is not a substitute for your own parental judgment, common sense, or professional advice</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 4 }}>• Every child is unique, and general tips may not be appropriate or safe for your specific child</p>
        <p style={{ margin: 0, paddingLeft: 16, marginBottom: 12 }}>• You will always prioritize the advice of qualified professionals over any content from MomzVeda</p>
        <p style={{ margin: 0, fontWeight: 700 }}>You hereby release and forever discharge MomzVeda Parties from any and all claims, demands, damages, losses, costs, expenses, and liability of every kind and nature, known and unknown, arising out of or in any way connected with your use of the Service.</p>
      </div>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>7. Indemnification</h2>
      <p>You agree to indemnify, defend, and hold harmless MomzVeda Parties from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any rights of any third party; or (d) any actions taken based on content provided by the Service.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>8. No Warranties</h2>
      <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, RELIABILITY, OR AVAILABILITY. MOMZVEDA DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF HARMFUL COMPONENTS. MOMZVEDA DOES NOT WARRANT THAT ANY INFORMATION PROVIDED IS ACCURATE, COMPLETE, RELIABLE, CURRENT, OR APPROPRIATE FOR ANY PARTICULAR PURPOSE.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>9. Emergency Situations</h2>
      <p>MomzVeda is NOT an emergency service. If you or your child are experiencing a medical emergency, mental health crisis, or any situation requiring immediate professional attention, call your local emergency number (such as 911 in the United States) or go to the nearest emergency room immediately. Do NOT rely on MomzVeda for emergency situations under any circumstances. While the Service may provide links to crisis resources, it is your sole responsibility to seek appropriate professional help when needed.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>10. Age Requirement</h2>
      <p>The Service is intended for use by adults aged 18 and older. By using MomzVeda, you confirm that you are at least 18 years of age. The Service is designed for parents, caregivers, and guardians — not for use by minors.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>11. User Conduct</h2>
      <p>You agree to use the Service responsibly and lawfully. You shall not: use the Service for any illegal purpose; attempt to gain unauthorized access to our systems; interfere with or disrupt the Service; use the Service to harm, threaten, or harass any person; impersonate any person or entity; or use the Service in any manner that could damage, disable, or impair the Service.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>12. Intellectual Property</h2>
      <p>All content, branding, design, logos, text, graphics, software, and code associated with MomzVeda are the property of MomzVeda and are protected by applicable intellectual property laws. You may not reproduce, distribute, modify, create derivative works from, publicly display, or commercially exploit any portion of the Service without our prior written consent.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>13. Third-Party Services</h2>
      <p>MomzVeda uses third-party services (including AI providers) to operate. We are not responsible for the practices, policies, or content of any third-party services. Your interactions with third-party services are governed by their own terms and policies.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>14. Maximum Liability Cap</h2>
      <p>IN NO EVENT SHALL THE TOTAL LIABILITY OF MOMZVEDA PARTIES TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION EXCEED THE AMOUNT YOU HAVE PAID TO MOMZVEDA IN THE TWELVE (12) MONTHS PRIOR TO THE CLAIM, OR TEN US DOLLARS ($10.00), WHICHEVER IS LESS.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>15. Dispute Resolution</h2>
      <p>Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved through binding arbitration on an individual basis. You waive any right to participate in a class action lawsuit or class-wide arbitration against MomzVeda. This arbitration provision shall survive termination of these Terms.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>16. Severability</h2>
      <p>If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect and enforceable.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>17. Changes to Terms</h2>
      <p>We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of the Service after any changes constitutes your acceptance of the updated Terms. It is your responsibility to review these Terms periodically.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>18. Governing Law</h2>
      <p>These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which MomzVeda operates, without regard to its conflict of law provisions.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>19. Entire Agreement</h2>
      <p>These Terms, together with our Privacy Policy, constitute the entire agreement between you and MomzVeda regarding the Service and supersede all prior agreements, understandings, and communications.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>20. Contact</h2>
      <p>For questions about these Terms of Service, contact us at <strong>legal@momzveda.com</strong>.</p>

      <div style={{ marginTop: 48, padding: '24px 0', borderTop: '1px solid #D5E8DC', fontSize: 13, color: '#6B9A7E' }}>
        © 2026 MomzVeda. All rights reserved.
      </div>
    </div>
  );
}
